spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db?useSSL=false
    username: bestuser
    password: bestuser
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8086