spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db?useSSL=false
    username: bestuser
    password: bestuser
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8086
#commit_1 branch-2
#commit_2 branch-2
#commit_3 branch-2
#commit_4 branch-2
#commit_5 branch-2
#commit_6 branch-2
#commit_7 branch-2
#commit_8 branch-2
#commit_9 branch-2
#commit_10 branch-2